### ISSUE TITLE
various language not available in GUI

### ISSUE THREAD

**Issue by lbesnard** [linuxserver/docker-digikam#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

In the digikam UI, I would expect to be able to change the language of the program

## Current Behavior

Currently, this is not possible, only English is available.

I tried adding the following environment variables in my docker-compose config"
```yaml
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=language-pack-kde-fr
```

However it doesn't seem to help

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:** ubuntu server 22.04, 5.15 kernel
**CPU architecture:** x86_64
**How docker service was installed:**

docker-compose

## Command used to create docker container (run/create/compose/screenshot)

```yaml
   digikam:
     image: lscr.io/linuxserver/digikam:latest
     container_name: digikam
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/Paris
       - KEYBOARD=fr-fr-azerty
       - DOCKER_MODS=linuxserver/mods:universal-package-install
       - INSTALL_PACKAGES=language-pack-kde-fr
     volumes:
       - $DOCKER_CONFIG_PATH/digikam:/config
       - $PICTURES_PATH:/pictures
     ports:
       - 3001:3000```
```
